version: "3"
services:
  apiserver:
    container_name: company-srv
    restart: always
    build: ./server
    ports:
      - "1337:1337"
    links:
      - mongo
  ui:
    container_name: company-ui
    restart: always
    build: ./ui
    depends_on:
      - apiserver
    ports:
      - "80:80"
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
