export const AUTH_LOG_IN_REQUEST                    = "AUTH_LOG_IN_REQUEST";
export const AUTH_LOG_IN_REQUEST_SUCCESS            = "AUTH_LOG_IN_REQUEST_SUCCESS";
export const AUTH_LOG_IN_REQUEST_FAIL               = "AUTH_LOG_IN_REQUEST_FAIL";
export const SET_TOKEN                              = "SET_TOKEN";

export const AUTH_SIGN_UP_REQUEST                   = "AUTH_SIGN_UP_REQUEST";
export const AUTH_SIGN_UP_REQUEST_SUCCESS           = "AUTH_SIGN_UP_REQUEST_SUCCESS";
export const AUTH_SIGN_UP_REQUEST_FAIL              = "AUTH_SIGN_UP_REQUEST_FAIL";

export const AUTH_LOG_OUT_REQUEST                   = "AUTH_LOG_OUT_REQUEST";
export const AUTH_LOG_OUT_REQUEST_SUCCESS           = "AUTH_LOG_OUT_REQUEST_SUCCESS";
export const AUTH_LOG_OUT_REQUEST_FAIL              = "AUTH_LOG_OUT_REQUEST_FAIL";


export const GET_USER_BY_ID                         = "GET_USER_BY_ID";
export const GET_USER_BY_ID_SUCCESS                 = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAIL                    = "GET_USER_BY_ID_FAIL";

export const PUT_USER_BY_ID                         = "PUT_USER_BY_ID";
export const PUT_USER_BY_ID_SUCCESS                 = "PUT_USER_BY_ID_SUCCESS";
export const PUT_USER_BY_ID_FAIL                    = "PUT_USER_BY_ID_FAIL";


export const GET_COMPANIES                          = "GET_COMPANIES";
export const GET_COMPANIES_SUCCESS                  = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAIL                     = "GET_COMPANIES_FAIL";

export const GET_COMPANIES_BY_ID                    = "GET_COMPANIES_BY_ID";
export const GET_COMPANIES_BY_ID_SUCCESS            = "GET_COMPANIES_BY_ID_SUCCESS";
export const GET_COMPANIES_BY_ID_FAIL               = "GET_COMPANIES_BY_ID_FAIL";

export const PUT_COMPANIES_BY_ID                    = "PUT_COMPANIES_BY_ID";
export const PUT_COMPANIES_BY_ID_SUCCESS            = "PUT_COMPANIES_BY_ID_SUCCESS";
export const PUT_COMPANIES_BY_ID_FAIL               = "PUT_COMPANIES_BY_ID_FAIL";

export const POST_NEW_COMPANY                       = "POST_NEW_COMPANY";
export const POST_NEW_COMPANY_SUCCESS               = "POST_NEW_COMPANY_SUCCESS";
export const POST_NEW_COMPANY_FAIL                  = "POST_NEW_COMPANY_FAIL";

export const DELETE_COMPANY                         = "DELETE_COMPANY";
export const DELETE_COMPANY_SUCCESS                 = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL                    = "DELETE_COMPANY_FAIL";


/* --- SORT ---  */
export const GET_COMPANIES_SORT_BY_NAME_UP              = "GET_COMPANIES_SORT_BY_NAME_UP";
export const GET_COMPANIES_SORT_BY_NAME_UP_SUCCESS      = "GET_COMPANIES_SORT_BY_NAME_UP_SUCCESS";
export const GET_COMPANIES_SORT_BY_NAME_UP_FAIL         = "GET_COMPANIES_SORT_BY_NAME_UP_FAIL";

export const GET_COMPANIES_SORT_BY_NAME_DESC            = "GET_COMPANIES_SORT_BY_NAME_DESC";
export const GET_COMPANIES_SORT_BY_NAME_DESC_SUCCESS    = "GET_COMPANIES_SORT_BY_NAME_DESC_SUCCESS";
export const GET_COMPANIES_SORT_BY_NAME_DESC_FAIL       = "GET_COMPANIES_SORT_BY_NAME_DESC_FAIL";

export const GET_COMPANIES_SORT_BY_SERVES_UP            = "GET_COMPANIES_SORT_BY_SERVES_UP";
export const GET_COMPANIES_SORT_BY_SERVES_UP_SUCCESS    = "GET_COMPANIES_SORT_BY_SERVES_UP_SUCCESS";
export const GET_COMPANIES_SORT_BY_SERVES_UP_FAIL       = "GET_COMPANIES_SORT_BY_SERVES_UP_FAIL";

export const GET_COMPANIES_SORT_BY_SERVES_DESC          = "GET_COMPANIES_SORT_BY_SERVES_DESC";
export const GET_COMPANIES_SORT_BY_SERVES_DESC_SUCCESS  = "GET_COMPANIES_SORT_BY_SERVES_DESC_SUCCESS";
export const GET_COMPANIES_SORT_BY_SERVES_DESC_FAIL     = "GET_COMPANIES_SORT_BY_SERVES_DESC_FAIL";

export const GET_COMPANIES_SORT_BY_NUMBER_UP            = "GET_COMPANIES_SORT_BY_NUMBER_UP";
export const GET_COMPANIES_SORT_BY_NUMBER_UP_SUCCESS    = "GET_COMPANIES_SORT_BY_NUMBER_UP_SUCCESS";
export const GET_COMPANIES_SORT_BY_NUMBER_UP_FAIL       = "GET_COMPANIES_SORT_BY_NUMBER_UP_FAIL";

export const GET_COMPANIES_SORT_BY_NUMBER_DESC          = "GET_COMPANIES_SORT_BY_NUMBER_DESC";
export const GET_COMPANIES_SORT_BY_NUMBER_DESC_SUCCESS  = "GET_COMPANIES_SORT_BY_NUMBER_DESC_SUCCESS";
export const GET_COMPANIES_SORT_BY_NUMBER_DESC_FAIL     = "GET_COMPANIES_SORT_BY_NUMBER_DESC_FAIL";
